---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tal-frontend
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tal-frontend
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: tal-frontend
    spec:
      containers:
      - name: tal-frontend
        image: gcr.io/arabic-historical-dictionary/tal-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tal-frontend
  namespace: default
  labels:
    app: tal-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tal-frontend
  type: LoadBalancer
  loadBalancerIP: "35.208.43.157"
